CREATE SCHEMA sneakers;
USE sneakers;

CREATE TABLE users (
id INT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT  NULL,
email VARCHAR(255) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
username VARCHAR(150),
nacimiento VARCHAR(150),
createdAt DATETIME,
updatedAt DATETIME,
deletedAt DATETIME
);

CREATE TABLE products (
id INT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT  NULL,
marca VARCHAR(255) UNIQUE NOT NULL,
modelo VARCHAR(255) UNIQUE NOT NULL,
fecha_de_lanzamiento VARCHAR(255) UNIQUE NOT NULL,
descripcion VARCHAR(255) UNIQUE NOT NULL,
createdAt DATETIME,
updatedAt DATETIME,
deletedAt DATETIME
);

CREATE TABLE comments (
id INT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT  NULL,
username VARCHAR(255) UNIQUE NOT NULL,
comentario VARCHAR(150),
createdAt DATETIME,
updatedAt DATETIME,
deletedAt DATETIME
);

