const database ={
    usuario:{
        usuario:'Bautista Martinez Baeza',
        contraseña:'Progra',
        nacimiento:'03/01/2003',
        fotodeperfil:'fotodeperfil.jpg'
    },
    productos:[
        {
            marca: "Jordan",
            modelo: "1 Retro Low OG SP",
            color:"Georgetown",
            imagen:"/images/sneakers/retro.png",
            comentarios:"Travis Scott agrega otro nuevo diseño a su relación de colaboración con Jumpman a través del Air Jordan 1 Low ",
            id: 1,
        },
        {
            marca: "Nike",
            modelo: "Dunk Low Retro",
            color:"White Black",
            imagen:"/images/sneakers/panda.png",
            comentarios:"Desde el College Colors Program con espíritu escolar hasta la vibrante colección Nike",
            id: 2,
        },
        {
            marca: "Adidas",
            modelo: "Yeezy Boost 350 V2",
            color:"Triple White",
            imagen:"/images/sneakers/yeezy.png",
            comentarios:"El adidas Yeezy Boost 350 V2 de color luminoso tiene una parte superior de color blanco crema,",
            id: 3,
        },
        {
            marca: "Nike",
            modelo: "Dunk Low",
            color:"Championship Court Purple",
            imagen:"/images/sneakers/dunk.png",
            comentarios:"El Nike Dunk Low Championship Purple presenta una parte superior de cuero blanco con superposiciones Championship Purple y Swooshes",
            id: 4,
        },
        {
            marca: "Jordan",
            modelo: "1 Retro High",
            color:"Bloodline",
            imagen:"/images/sneakers/retrohigh.png",
            comentarios:"Jordan Brand rinde homenaje al lugar donde comenzó el legado con Jordan 1 Retro High Bloodline",
            id: 5,
        },
        {
            marca: "Jordan",
            modelo: "4 Retro",
            color:"Lightning",
            imagen:"/images/sneakers/retro4.png",
            comentarios:"Lanzado originalmente en 2006, el Air Jordan 4 Retro Lightning (2021) es una de las combinaciones de colores retro Jordan 4 más reconocidas en el catálogo de la marca Jordan",
            id: 6,
        },
        {
            marca: "Adidas",
            modelo: "Yeezy Foam RNNR",
            color:"Ochre",
            imagen:"/images/sneakers/foam.png",
            comentarios:"El adidas Yeezy Foam RNNR Ochre presenta una construcción de espuma EVA de una sola pieza Ochre dorado",
            id: 7,
        },
        {
            marca: "Adidas",
            modelo: "Yeezy 450",
            color:"Dark Slate",
            imagen:"/images/sneakers/450.png",
            comentarios:"Con una construcción simplificada de dos piezas, el adidas Yeezy 450 Dark Slate presenta una suela de espuma Dark Slate que se ajusta a una parte superior Primeknit monocromática similar a un calcetín",
            id: 8,
        },
        {
            marca: "Nike",
            modelo: "Dunk Low",
            color:"Laser Orange",
            imagen:"/images/sneakers/dunkamarilllas.png",
            comentarios:"Las Nike Dunk Low Laser Orange (W) para mujer llegan con una parte superior de cuero blanco y revestimientos Laser Orange",
            id: 9,
        },
        {
            marca: "Nike",
            modelo: "SB Dunk Low",
            color:"Travis Scott",
            imagen:"/images/sneakers/travis.png",
            comentarios:"Travis Scott se asoció con Nike SB para lanzar su primer calzado de skate oficial",
            id: 10,
        },
        {
            marca: "Nike",
            modelo: "SB Dunk Low",
            color:"StrangeLove Skateboards",
            imagen:"/images/sneakers/dunkpink.png",
            comentarios:"Nike SB celebró el Día de San Valentín al conectarse con los artistas legendarios Todd Bratrud y Sean Cliver para lanzar las patinetas Nike SB Dunk Low Strangelove (caja regular)",
            id: 11,
            
        },
        {
            marca: "Nike",
            modelo: "SB Blazer Mid",
            color:"Isle Skateboards",
            imagen:"/images/sneakers/blazer.png",
            comentarios:"Las famosas Blazer, renovadas",
            id: 12,
        },
        {
            marca: "Adidas",
            modelo: "Forum Low",
            color:"Bad Bunny Back to School",
            imagen:"/images/sneakers/forum.png",
            comentarios:"El adidas Forum Low Bad Bunny Back To School presenta una parte superior triple de cuero negro y gamuza sobre una suela negra",
            id: 13,
        },
        {
            marca: "New Balance",
            modelo: "550",
            color:"Aime Leon Dore White Grey",
            imagen:"/images/sneakers/550.png",
            comentarios:"Aimè Leon Dore se asoció con New Balance para traer de vuelta las New Balance 550, una silueta de basquetbol de caña baja presentada originalmente en 1989 como New Balance P550",
            id: 14,
        },
        {
            marca: "Umbro",
            modelo: "F5 Model 1",
            color:"Black School",
            imagen:"/images/sneakers/umbro.jpeg",
            comentarios:"Tanto como para un partido como para ir al colegio",
            id: 15,
        },
    ]
}
    


module.exports = database;